### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by binary132** [synapse-garden/mf-proto#12]
We need an admin CLI.

That could be implemented a number of ways.  For now, the simplest way would be to have a console readline.

[main.go:22](https://github.com/synapse-garden/mf-proto/blob/master/main.go#L22-L23) should probably have something like this:

``` go
    // ...
    commands := make(chan string)
    go readCommands(commands)

    for command := range commands {
        // do something interesting
    }
}

func readCommands(c chan string) {
    reader := bufio.NewReader(os.Stdin)
    for {
        fmt.Print(" > ")
        command, err := reader.ReadString('\n')
        if err != nil {
            log.Panic(err)
        }
        c <- command
    }
}
```

**Comment by chzyer** [comment]
Would you mind to try this one:) https://github.com/chzyer/readline

**Comment by binary132** [comment]
Cool :) I'll definitely have a look at this!  Thanks @chzyer

**Comment by binary132** [comment]
Thanks again @chzyer, mf-proto is now using your readline package.
